# -*- coding: utf-8 -*-
"""3W.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8FAL5cwWuC1sJdXocPvF5w91dhu2hGY
"""

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/merged.csv')

numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].mean())

categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

from sklearn.preprocessing import LabelEncoder
le_state = LabelEncoder()
df['state'] = le_state.fit_transform(df['state'])

corr_matrix = df.corr()
top_corr_features = corr_matrix['state'].drop('state').abs().sort_values(ascending=False)
selected_features = top_corr_features.head(10).index.tolist()
print("Selected features:", selected_features)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df[selected_features].values
y = df['state'].values

scaler = StandardScaler()
X = scaler.fit_transform(X)

X = X.reshape(X.shape[0], X.shape[1], 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Commented out IPython magic to ensure Python compatibility.
# %pip install tensorflow

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np

model = models.Sequential([
    layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=(X.shape[1], 1)),
    layers.MaxPooling1D(pool_size=2),
    layers.Conv1D(32, kernel_size=3, activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(len(np.unique(y)), activation='softmax')  # output layer
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=10, validation_split=0.2, batch_size=32)

# Evaluate on test set
loss, acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {acc:.2f}")

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('CNN Training vs Validation Accuracy')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

for col in selected_features[:6]:
    plt.figure(figsize=(8, 5))
    sns.boxplot(data=df, x='state', y=col, palette='pastel')
    plt.title(f'{col} by State')
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.show()

plt.figure(figsize=(12, 10))
corr = df[selected_features + ['state']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap of Selected Features with State")
plt.show()

state_corr = df.corr()['state'].drop('state').sort_values(key=abs, ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=state_corr.values, y=state_corr.index, palette='viridis')
plt.title("Correlation of Features with State")
plt.xlabel("Correlation")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Plot distribution of top correlated features
for col in selected_features:
    plt.figure(figsize=(6, 4))
    sns.histplot(df[col], kde=True, bins=30, color='skyblue')
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.show()

plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='state', palette='Set2')
plt.title("Frequency of Each State Class")
plt.xlabel("State")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

new_input = {
    'P-PDG': 1500,
    'P-TPT': 1400,
    'T-PDG': 90,
    'T-TPT': 85,
    'QGL': 40,
    'P-JUS-CKGL': 1800,
    'P-MON-CKGL': 1700,
    'P-ANULAR': 1600,
    'T-MON-CKP': 75,
    'QBS': 50
}
import numpy as np
new_df = pd.DataFrame([new_input])
new_scaled = scaler.transform(new_df)
new_scaled = new_scaled.reshape(1, len(selected_features), 1)
predicted_class_index = np.argmax(model.predict(new_scaled), axis=-1)[0]
predicted_state = le_state.inverse_transform([predicted_class_index])[0]
print("Predicted State:", predicted_state)