# -*- coding: utf-8 -*-
"""Health Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JM-X2nil_0lNMilxgQL8-j8gLLthHzKe
"""

import pandas as pd
import os
from pathlib import Path

# Seyt the parent directory that contains folders 0 to 9
base_dir = Path("/content/drive/MyDrive/Seminar Running Notes and PDF'S - Copy/ML")  # e.g., "data" if folders are inside ./data

# Initialize an empty list to collect DataFrames
all_dfs = []

# Loop through folder names 0 to 9
for i in range(10):
    folder_path = base_dir / str(i)
    if folder_path.exists():
        for file in folder_path.glob("*.parquet"):
            df = pd.read_parquet(file)
            all_dfs.append(df)

# Concatenate all DataFrames
combined_df = pd.concat(all_dfs, ignore_index=True)

# Save to CSV
combined_df.to_csv("3wdataset.csv", index=False)

print("Conversion complete. Saved to combined_output.csv")

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

ds = "/content/drive/MyDrive/Seminar Running Notes and PDF'S - Copy/ML"
data = []
for i in range(7):
    path = os.path.join(ds, str(i))
    if not os.path.isdir(path):
        continue
    for file in os.listdir(path):
        if file.endswith(".parquet"):
            file_path = os.path.join(path, file)
            try:
                df = pd.read_parquet(file_path)
                data.append(df)
                print(f"Loaded: {file_path}")
            except Exception as e:
                print(f"Failed to load {file_path}: {e}")
if data:
    new_df = pd.concat(data, ignore_index=True)
    print("\nAll data successfully combined!")
    print("Final Dataset Shape:", new_df.shape)
else:
    print("No data files found!")

num = new_df.select_dtypes(include=['float64', 'int64'])

# Correlation heatmap of only numerical features
plt.figure(figsize=(14, 10))
sns.heatmap(num.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("📊 Feature Correlation Heatmap (Numerical Features Only)")
plt.tight_layout()
plt.show()

#Calculate correlation matrix
cmatrix = num.corr().abs()

#Mask diagonal and lower triangle (to avoid duplicate pairs)
upper  = cmatrix.where(np.triu(np.ones(cmatrix.shape), k=1).astype(bool))

#Select features that have high correlation with at least one other feature
threshold = 0.6  # You can adjust this threshold
features = [column for column in upper.columns if any(upper[column] > threshold)]
print(features)

np.random.seed(42)
sample_size = 1000

# Selected features
selected_features = [
    'ABER-CKP', 'ESTADO-SDV-GL', 'ESTADO-W1', 'ESTADO-W2',
    'P-JUS-CKGL', 'P-MON-CKP', 'P-PDG', 'QGL',
    'T-JUS-CKP', 'T-PDG', 'T-TPT'
]

# Generate synthetic data
new_df = pd.DataFrame(np.random.rand(sample_size, len(selected_features)), columns=selected_features)
new_df['health_status'] = np.random.choice(['healthy', 'warning', 'faulty'], size=sample_size)  # Target

# Separate features and target
X = new_df[selected_features]
y = new_df['health_status']

# Encode target labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluation
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_, cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

# Re-import everything after reset
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

# Step 1: Load the CSV dataset directly
csv_path = "/content/3wdataset.csv"
new_df = pd.read_csv(csv_path)

print(new_df.info())

print(new_df.head())

print(new_df.isnull().sum())

print(new_df.columns)

# Step 4: Drop irrelevant columns if they exist
cdrop = ['timestamp', 'well_id']
new_df.drop(columns=[col for col in cdrop if col in new_df.columns], inplace=True)

# Step 7: Manually specify selected features (Ensure these columns exist in your CSV data)
selected_features = [
    'ABER-CKP', 'ESTADO-SDV-GL', 'ESTADO-W1', 'ESTADO-W2',
    'P-JUS-CKGL', 'P-MON-CKP', 'P-PDG', 'QGL',
    'T-JUS-CKP', 'T-PDG', 'T-TPT'
]

# *** IMPORTANT FIX: Replace 'health_status' with the actual name of your target column ***
# Step 8: Filter to selected features and your actual target column
# You need to replace 'YOUR_TARGET_COLUMN_NAME' with the name of the column in your CSV
# that you intend to use as the target variable.
target_column_name = 'ESTADO-W1' # <--- Replace with your actual target column name!

# Check if the target column exists before proceeding
if target_column_name not in new_df.columns:
    print(f"Error: Target column '{target_column_name}' not found in the dataset.")
    print("Please check the column names in your CSV file and update 'target_column_name'.")
    # You might want to add a way to stop execution or handle this error gracefully
else:
    # Ensure selected_features also exist, only keep those that do
    valid_selected_features = [feat for feat in selected_features if feat in new_df.columns]
    if len(valid_selected_features) != len(selected_features):
        missing_features = list(set(selected_features) - set(valid_selected_features))
        print(f"Warning: The following selected features were not found in the dataset: {missing_features}")
        print("Proceeding with the features that were found.")

    filtered_df = new_df[valid_selected_features + [target_column_name]].dropna()

    # Step 9: Prepare features and labels
    X = filtered_df[valid_selected_features]
    y = filtered_df[target_column_name]

    # Step 10: Encode target labels
    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)

    # Step 11: Scale features
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Step 12: Split data
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

    # Step 13: Train model
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Step 14: Predict
    y_pred = model.predict(X_test)

    # Step 15: Evaluation
    print("\n📈 Classification Report:")
    # Pass the classes from the encoder to target_names
    print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

    # Step 16: Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_, cmap='Blues')
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")
    plt.tight_layout()
    plt.show()

    # Step 17: Print Accuracy
    accuracy = model.score(X_test, y_test)
    print(f"\n✅ Model Accuracy: {accuracy:.2f}")