# -*- coding: utf-8 -*-
"""PDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HPJvjmIRQmwOcRvSTGVHg0YQg1Abkrp
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install xgboost

#importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
import warnings
warnings.filterwarnings("ignore")

#dataset loading / reading
df = pd.read_csv('/content/drive/MyDrive/predictive_maintenance.csv')

"""EDA"""

df.shape

df.head()

df.isnull().sum()

df.dtypes

df.describe()

df1 = df.copy()

df1.drop(['UDI','Product ID'], axis=1, inplace=True)

df1.head()

df1.rename(columns={'Type':'type', 'Air temperature [K]':'air_temp',
                    'Process temperature [K]':'process_temp', 'Rotational speed [rpm]':'rotational_speed',
                   'Torque [Nm]': 'torque', 'Tool wear [min]':'tool_wear', 'Target':'failure',
                    'Failure Type':'failure_type'}, inplace=True)

df1.columns

print('Column Name : Number of Unique Values')
for col in df1.columns:
    print(f'{col} : {len(df1[col].unique())}')

targets = {0:'No Failure', 1:'Failure'}
df1['failure'] = df1['failure'].map(targets)

df1.head()

sns.pairplot(df1, hue='failure')

categorical_cols = []
numerical_cols = []
for col in df1.columns:
    if df1[col].dtype == object:
        categorical_cols.append(col)
    else:
        numerical_cols.append(col)

categorical_cols

numerical_cols

idx_amb = df1[(df1['failure'] == 'Failure') & (df1['failure_type'] == 'No Failure')].index

df1 = df1.drop(idx_amb, axis=0)
df1.shape

plt.figure(figsize=(15,15))
for i, col in enumerate(numerical_cols):
    plt.subplot(3,2,i+1)
    sns.histplot(data = df1, x=col, hue='failure', kde=True)
    plt.title(f'{col}')

plt.figure(figsize=(15,15))
for i, col in enumerate(numerical_cols):
    plt.subplot(3,2,i+1)
    sns.histplot(data = df1, x=col, hue='failure_type', kde=True)
    plt.title(f'{col}')

plt.figure(figsize=(15,15))
for i, col in enumerate(numerical_cols):
    plt.subplot(3,2,i+1)
    sns.histplot(data = df1, x=col, hue='type', kde=True)
    plt.title(f'{col}')

plt.figure(figsize=(15,10))
for i, col in enumerate(numerical_cols):
    plt.subplot(2,3,i+1)
    sns.boxplot(data = df1, x=col, hue='type')
    plt.title(f'{col}')

dff = df1[df1['failure'] == 'Failure']
dff.shape

plt.figure(figsize=(15,15))
for i, col in enumerate(numerical_cols):
    plt.subplot(3,2,i+1)
    sns.histplot(data = dff, x=col, hue='type', kde=True)
    plt.title(f'{col}')

plt.figure(figsize=(15,15))
for i, col in enumerate(numerical_cols):
    plt.subplot(3,2,i+1)
    sns.histplot(data = dff, x=col, hue='failure_type', kde=True)
    plt.title(f'{col}')

plt.pie(df1['failure'].value_counts(), labels = df1['failure'].value_counts().index, autopct='%1.2f%%')
plt.title('Failures')
plt.legend()
plt.show()

plt.pie(df1['type'].value_counts(), labels = df1['type'].value_counts().index, autopct='%1.2f%%')
plt.title('Types')
plt.legend()
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %pip install imbalanced-learn

from imblearn.over_sampling import SMOTE

df1['failure_type'].value_counts()

df2 =df1.copy()

print('Column Name : Unique Values')
for col in categorical_cols:
    print(f'{col} : {df2[col].unique()}')

typ = {'L': 0, 'M': 1, 'H': 2}
ftype = {'No Failure': 0, 'Power Failure': 1, 'Overstrain Failure': 2,
                       'Heat Dissipation Failure': 3, 'Tool Wear Failure': 4}
fail = {'No Failure':0, 'Failure':1}

df2['type'] = df2['type'].map(typ)
df2['failure_type'] = df2['failure_type'].map(ftype)
df2['failure'] = df2['failure'].map(fail)

sns.heatmap(df2.corr(), annot=True, fmt='0.2f', cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

X = df2.drop(['failure', 'failure_type'], axis=1)
y = df2['failure']
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=42)
smote = SMOTE(random_state=42)
X_res, Y_res = smote.fit_resample(X_train, Y_train)

X_res.describe()

X_res

Y_res

scaler=StandardScaler()
X_res[numerical_cols] = scaler.fit_transform(X_res[numerical_cols])

features = X_res[['process_temp', 'rotational_speed', 'tool_wear']]
target = Y_res

x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=0)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

# XGBoost Model
xgb = XGBClassifier(random_state=42)
xgb.fit(x_train, y_train)

y_pred_xgb = xgb.predict(x_test)

print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

# Gradient Boosting Model
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(x_train, y_train)

y_pred_gb = gb_model.predict(x_test)

print(confusion_matrix(y_test, y_pred_gb))
print(classification_report(y_test, y_pred_gb))
print("Accuracy:", accuracy_score(y_test, y_pred_gb))

from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, confusion_matrix, classification_report

# STEP 1: Drop ambiguous and missing rows
df2 = df.copy()
df2.drop(['UDI', 'Product ID'], axis=1, inplace=True)
df2.rename(columns={
    'Type': 'type',
    'Air temperature [K]': 'air_temp',
    'Process temperature [K]': 'process_temp',
    'Rotational speed [rpm]': 'rotational_speed',
    'Torque [Nm]': 'torque',
    'Tool wear [min]': 'tool_wear',
    'Target': 'failure',
    'Failure Type': 'failure_type'
}, inplace=True)

# Mapping categorical values
df2['type'] = df2['type'].map({'L': 0, 'M': 1, 'H': 2})
df2['failure'] = df2['failure'].map({'No Failure': 0, 'Failure': 1})
df2['failure_type'] = df2['failure_type'].map({
    'No Failure': 0,
    'Power Failure': 1,
    'Overstrain Failure': 2,
    'Heat Dissipation Failure': 3,
    'Tool Wear Failure': 4
})

# Remove invalid combinations and NaNs
df2 = df2[~((df2['failure'] == 1) & (df2['failure_type'] == 0))]
df2 = df2.dropna(subset=['failure_type'])

# Feature-target split
X_ftype = df2.drop(['failure', 'failure_type'], axis=1)
y_ftype = df2['failure_type']

# Train/test split
X_train_ftype, X_test_ftype, y_train_ftype, y_test_ftype = train_test_split(
    X_ftype, y_ftype, test_size=0.3, random_state=42
)

# Scaling
scaler = StandardScaler()
X_train_ftype_scaled = scaler.fit_transform(X_train_ftype)
X_test_ftype_scaled = scaler.transform(X_test_ftype)

# Model training
rf_model = GradientBoostingClassifier(random_state=42)
rf_model.fit(X_train_ftype_scaled, y_train_ftype)

# Evaluation
y_pred_ftype = rf_model.predict(X_test_ftype_scaled)
print("Confusion Matrix:\n", confusion_matrix(y_test_ftype, y_pred_ftype))
print("\nClassification Report:\n", classification_report(y_test_ftype, y_pred_ftype))
print("\nAccuracy:", accuracy_score(y_test_ftype, y_pred_ftype))

def predict_failure_type(input_data):
    # Map type to numeric
    type_map = {'L': 0, 'M': 1, 'H': 2}
    input_data['type'] = type_map.get(input_data['type'], 0)

    # Convert to DataFrame and scale
    input_df = pd.DataFrame([input_data])
    input_scaled = scaler.transform(input_df)

    # Predict and convert to integer index
    prediction = int(rf_model.predict(input_scaled)[0])

    # Failure type labels
    labels = ['No Failure', 'Power Failure', 'Overstrain Failure',
              'Heat Dissipation Failure', 'Tool Wear Failure']

    return labels[prediction]

sample = {
    'type': 'H',
    'air_temp': 298.5,
    'process_temp': 308.9,
    'rotational_speed': 1600,
    'torque': 42.0,
    'tool_wear': 10
}

print("Predicted Failure Type:", predict_failure_type(sample))